services:
  - type: web
    name: honeycomb-game-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SOLANA_RPC
        value: https://rpc.test.honeycombprotocol.com/
      - key: HONEYCOMB_API_URL
        value: https://edge.test.honeycombprotocol.com/
      - key: OLD_TREASURER_PRIVATE_KEY
        value: ""
      - key: HONEYCOMB_PROJECT_ID
        value: "[your_project_id]"
      - key: TREASURER_PUBLIC_KEY
        value: Ea11c8R536WGzMje5pDz8sUkYqyu3mo8txyXhYHmDfj7
      - key: PROJECT_PUBKEY
        value: BkF2wCJirExrRYva4YcHMHqdnrZJENWbZkN1o84ZQHa8
